var dbAPI = require('../../nodeServer/sourceCode/entitiesUtils/entitiesFactory').EntitiesFactory;

var user = dbAPI.getUserEntity();

email1 = "admin@admin";
password1 = "@dm1n";
name1 = "Admin";
surname1 = "Admin";
company1 = "Company";
mobilephone1 = "0000000000";

var query = {
    //pKey : "start-email:"+email1+";mobilephone:"+mobilephone1+"-end", // autogenerated
    email : email1,
    password : password1,
    name : name1,
    surname : surname1,
    company : company1,
    mobilephone : mobilephone1
}

var data = {}
data.query = query
user.insert(data, function(err) {
    if(err)
        console.log("ERROR"+err);
    else 
        console.log("ADDED");
} )
