var dbAPI = require('../../mongoDb/publicDbAPI/publicDBApi').publicDBApi;

var user = dbAPI.getUserEntity();

email1 = "adem.hoxha91@gmail.com";
password1 = "nopswd";
name1 = "Adem";
surname1 = "Hoxha";
company1 = "Company";
mobilephone1 = "00393287314829";

var query = {
    //pKey : "start-email:"+email1+";mobilephone:"+mobilephone1+"-end", // autogenerated
    email : email1,
    password : password1,
    name : name1,
    surname : surname1,
    company : company1,
    mobilephone : mobilephone1
}

var data = {}
data.query = query
user.insert(data, function(err) {
    if(err)
        console.log("ERROR"+err);
    else 
        console.log("ADDED");
} )
