// load db schema
var models = require('../entities/models').Models;
var entitiesFactory = require('mongodb-entities').entitiesFactory;
entitiesFactory.setModel(models);

var user = require('../entitiesUtils/entitiesFactory').EntitiesFactory.getUserEntity();
email1 = "guest@guest";
password1 = "guest";
name1 = "Guest";
surname1 = "Guest";
company1 = "Guest";
mobilephone1 = "0123456789";

var query = {
    //pKey : "start-email:"+email1+";mobilephone:"+mobilephone1+"-end", // autogenerated
    email : email1,
    password : password1,
    name : name1,
    surname : surname1,
    company : company1,
    mobilephone : mobilephone1
}

var data = {}
data.query = query
user.insert(data, function(err) {
    if(err)
        console.log("ERROR"+err);
    else 
        console.log("ADDED");
} )